//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AplikacjaSerwisowa.kwronski {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="galsoftsrv")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SayHelloToLameOperationCompleted;
        
        private System.Threading.SendOrPostCallback lamaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeKntAdresyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeKntKartyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeZlecenSerwisowychNaglowkiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeZlecenSerwisowychCzynnosciOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeZlecenSerwisowychSkladnikiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeTwrKartyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeSrwUrzRodzajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeSrwUrzadzeniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeSrwUrzRodzParOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeSrwUrzParDefOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListePodpisowOperationCompleted;
        
        private System.Threading.SendOrPostCallback synchronizujSrwZlcNagOperationCompleted;
        
        private System.Threading.SendOrPostCallback synchronizujSrwZlcCzynnosciOperationCompleted;
        
        private System.Threading.SendOrPostCallback synchronizujSrwZlcSkladnikiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocListeOperatorowOperationCompleted;
        
        private System.Threading.SendOrPostCallback GalSrv_SrwZlcNagOperationCompleted;
        
        private System.Threading.SendOrPostCallback GalSrv_SrwZlcNagPotwierdzenieOperationCompleted;
        
        private System.Threading.SendOrPostCallback GalSrv_SrwZlcCzynnosciOperationCompleted;
        
        private System.Threading.SendOrPostCallback GalSrv_SrwZlcCzynnosciPotwierdzenieOperationCompleted;
        
        private System.Threading.SendOrPostCallback GalSrv_SrwZlcSkladnikiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GalSrv_SrwZlcSkladnikiPotwierdzenieOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = "http://91.196.8.98:8080/WebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SayHelloToLameCompletedEventHandler SayHelloToLameCompleted;
        
        /// <remarks/>
        public event lamaCompletedEventHandler lamaCompleted;
        
        /// <remarks/>
        public event ZwrocListeKntAdresyCompletedEventHandler ZwrocListeKntAdresyCompleted;
        
        /// <remarks/>
        public event ZwrocListeKntKartyCompletedEventHandler ZwrocListeKntKartyCompleted;
        
        /// <remarks/>
        public event ZwrocListeZlecenSerwisowychNaglowkiCompletedEventHandler ZwrocListeZlecenSerwisowychNaglowkiCompleted;
        
        /// <remarks/>
        public event ZwrocListeZlecenSerwisowychCzynnosciCompletedEventHandler ZwrocListeZlecenSerwisowychCzynnosciCompleted;
        
        /// <remarks/>
        public event ZwrocListeZlecenSerwisowychSkladnikiCompletedEventHandler ZwrocListeZlecenSerwisowychSkladnikiCompleted;
        
        /// <remarks/>
        public event ZwrocListeTwrKartyCompletedEventHandler ZwrocListeTwrKartyCompleted;
        
        /// <remarks/>
        public event ZwrocListeSrwUrzRodzajeCompletedEventHandler ZwrocListeSrwUrzRodzajeCompleted;
        
        /// <remarks/>
        public event ZwrocListeSrwUrzadzeniaCompletedEventHandler ZwrocListeSrwUrzadzeniaCompleted;
        
        /// <remarks/>
        public event ZwrocListeSrwUrzRodzParCompletedEventHandler ZwrocListeSrwUrzRodzParCompleted;
        
        /// <remarks/>
        public event ZwrocListeSrwUrzParDefCompletedEventHandler ZwrocListeSrwUrzParDefCompleted;
        
        /// <remarks/>
        public event ZwrocListePodpisowCompletedEventHandler ZwrocListePodpisowCompleted;
        
        /// <remarks/>
        public event synchronizujSrwZlcNagCompletedEventHandler synchronizujSrwZlcNagCompleted;
        
        /// <remarks/>
        public event synchronizujSrwZlcCzynnosciCompletedEventHandler synchronizujSrwZlcCzynnosciCompleted;
        
        /// <remarks/>
        public event synchronizujSrwZlcSkladnikiCompletedEventHandler synchronizujSrwZlcSkladnikiCompleted;
        
        /// <remarks/>
        public event ZwrocListeOperatorowCompletedEventHandler ZwrocListeOperatorowCompleted;
        
        /// <remarks/>
        public event GalSrv_SrwZlcNagCompletedEventHandler GalSrv_SrwZlcNagCompleted;
        
        /// <remarks/>
        public event GalSrv_SrwZlcNagPotwierdzenieCompletedEventHandler GalSrv_SrwZlcNagPotwierdzenieCompleted;
        
        /// <remarks/>
        public event GalSrv_SrwZlcCzynnosciCompletedEventHandler GalSrv_SrwZlcCzynnosciCompleted;
        
        /// <remarks/>
        public event GalSrv_SrwZlcCzynnosciPotwierdzenieCompletedEventHandler GalSrv_SrwZlcCzynnosciPotwierdzenieCompleted;
        
        /// <remarks/>
        public event GalSrv_SrwZlcSkladnikiCompletedEventHandler GalSrv_SrwZlcSkladnikiCompleted;
        
        /// <remarks/>
        public event GalSrv_SrwZlcSkladnikiPotwierdzenieCompletedEventHandler GalSrv_SrwZlcSkladnikiPotwierdzenieCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/SayHelloToLame", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SayHelloToLame(string test) {
            object[] results = this.Invoke("SayHelloToLame", new object[] {
                        test});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SayHelloToLameAsync(string test) {
            this.SayHelloToLameAsync(test, null);
        }
        
        /// <remarks/>
        public void SayHelloToLameAsync(string test, object userState) {
            if ((this.SayHelloToLameOperationCompleted == null)) {
                this.SayHelloToLameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSayHelloToLameOperationCompleted);
            }
            this.InvokeAsync("SayHelloToLame", new object[] {
                        test}, this.SayHelloToLameOperationCompleted, userState);
        }
        
        private void OnSayHelloToLameOperationCompleted(object arg) {
            if ((this.SayHelloToLameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SayHelloToLameCompleted(this, new SayHelloToLameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/lama", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string lama() {
            object[] results = this.Invoke("lama", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void lamaAsync() {
            this.lamaAsync(null);
        }
        
        /// <remarks/>
        public void lamaAsync(object userState) {
            if ((this.lamaOperationCompleted == null)) {
                this.lamaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlamaOperationCompleted);
            }
            this.InvokeAsync("lama", new object[0], this.lamaOperationCompleted, userState);
        }
        
        private void OnlamaOperationCompleted(object arg) {
            if ((this.lamaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lamaCompleted(this, new lamaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeKntAdresy", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeKntAdresy() {
            object[] results = this.Invoke("ZwrocListeKntAdresy", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeKntAdresyAsync() {
            this.ZwrocListeKntAdresyAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeKntAdresyAsync(object userState) {
            if ((this.ZwrocListeKntAdresyOperationCompleted == null)) {
                this.ZwrocListeKntAdresyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeKntAdresyOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeKntAdresy", new object[0], this.ZwrocListeKntAdresyOperationCompleted, userState);
        }
        
        private void OnZwrocListeKntAdresyOperationCompleted(object arg) {
            if ((this.ZwrocListeKntAdresyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeKntAdresyCompleted(this, new ZwrocListeKntAdresyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeKntKarty", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeKntKarty() {
            object[] results = this.Invoke("ZwrocListeKntKarty", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeKntKartyAsync() {
            this.ZwrocListeKntKartyAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeKntKartyAsync(object userState) {
            if ((this.ZwrocListeKntKartyOperationCompleted == null)) {
                this.ZwrocListeKntKartyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeKntKartyOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeKntKarty", new object[0], this.ZwrocListeKntKartyOperationCompleted, userState);
        }
        
        private void OnZwrocListeKntKartyOperationCompleted(object arg) {
            if ((this.ZwrocListeKntKartyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeKntKartyCompleted(this, new ZwrocListeKntKartyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeZlecenSerwisowychNaglowki", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeZlecenSerwisowychNaglowki() {
            object[] results = this.Invoke("ZwrocListeZlecenSerwisowychNaglowki", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeZlecenSerwisowychNaglowkiAsync() {
            this.ZwrocListeZlecenSerwisowychNaglowkiAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeZlecenSerwisowychNaglowkiAsync(object userState) {
            if ((this.ZwrocListeZlecenSerwisowychNaglowkiOperationCompleted == null)) {
                this.ZwrocListeZlecenSerwisowychNaglowkiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeZlecenSerwisowychNaglowkiOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeZlecenSerwisowychNaglowki", new object[0], this.ZwrocListeZlecenSerwisowychNaglowkiOperationCompleted, userState);
        }
        
        private void OnZwrocListeZlecenSerwisowychNaglowkiOperationCompleted(object arg) {
            if ((this.ZwrocListeZlecenSerwisowychNaglowkiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeZlecenSerwisowychNaglowkiCompleted(this, new ZwrocListeZlecenSerwisowychNaglowkiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeZlecenSerwisowychCzynnosci", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeZlecenSerwisowychCzynnosci() {
            object[] results = this.Invoke("ZwrocListeZlecenSerwisowychCzynnosci", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeZlecenSerwisowychCzynnosciAsync() {
            this.ZwrocListeZlecenSerwisowychCzynnosciAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeZlecenSerwisowychCzynnosciAsync(object userState) {
            if ((this.ZwrocListeZlecenSerwisowychCzynnosciOperationCompleted == null)) {
                this.ZwrocListeZlecenSerwisowychCzynnosciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeZlecenSerwisowychCzynnosciOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeZlecenSerwisowychCzynnosci", new object[0], this.ZwrocListeZlecenSerwisowychCzynnosciOperationCompleted, userState);
        }
        
        private void OnZwrocListeZlecenSerwisowychCzynnosciOperationCompleted(object arg) {
            if ((this.ZwrocListeZlecenSerwisowychCzynnosciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeZlecenSerwisowychCzynnosciCompleted(this, new ZwrocListeZlecenSerwisowychCzynnosciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeZlecenSerwisowychSkladniki", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeZlecenSerwisowychSkladniki() {
            object[] results = this.Invoke("ZwrocListeZlecenSerwisowychSkladniki", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeZlecenSerwisowychSkladnikiAsync() {
            this.ZwrocListeZlecenSerwisowychSkladnikiAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeZlecenSerwisowychSkladnikiAsync(object userState) {
            if ((this.ZwrocListeZlecenSerwisowychSkladnikiOperationCompleted == null)) {
                this.ZwrocListeZlecenSerwisowychSkladnikiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeZlecenSerwisowychSkladnikiOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeZlecenSerwisowychSkladniki", new object[0], this.ZwrocListeZlecenSerwisowychSkladnikiOperationCompleted, userState);
        }
        
        private void OnZwrocListeZlecenSerwisowychSkladnikiOperationCompleted(object arg) {
            if ((this.ZwrocListeZlecenSerwisowychSkladnikiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeZlecenSerwisowychSkladnikiCompleted(this, new ZwrocListeZlecenSerwisowychSkladnikiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeTwrKarty", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeTwrKarty() {
            object[] results = this.Invoke("ZwrocListeTwrKarty", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeTwrKartyAsync() {
            this.ZwrocListeTwrKartyAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeTwrKartyAsync(object userState) {
            if ((this.ZwrocListeTwrKartyOperationCompleted == null)) {
                this.ZwrocListeTwrKartyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeTwrKartyOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeTwrKarty", new object[0], this.ZwrocListeTwrKartyOperationCompleted, userState);
        }
        
        private void OnZwrocListeTwrKartyOperationCompleted(object arg) {
            if ((this.ZwrocListeTwrKartyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeTwrKartyCompleted(this, new ZwrocListeTwrKartyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeSrwUrzRodzaje", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeSrwUrzRodzaje() {
            object[] results = this.Invoke("ZwrocListeSrwUrzRodzaje", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeSrwUrzRodzajeAsync() {
            this.ZwrocListeSrwUrzRodzajeAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeSrwUrzRodzajeAsync(object userState) {
            if ((this.ZwrocListeSrwUrzRodzajeOperationCompleted == null)) {
                this.ZwrocListeSrwUrzRodzajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeSrwUrzRodzajeOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeSrwUrzRodzaje", new object[0], this.ZwrocListeSrwUrzRodzajeOperationCompleted, userState);
        }
        
        private void OnZwrocListeSrwUrzRodzajeOperationCompleted(object arg) {
            if ((this.ZwrocListeSrwUrzRodzajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeSrwUrzRodzajeCompleted(this, new ZwrocListeSrwUrzRodzajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeSrwUrzadzenia", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeSrwUrzadzenia() {
            object[] results = this.Invoke("ZwrocListeSrwUrzadzenia", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeSrwUrzadzeniaAsync() {
            this.ZwrocListeSrwUrzadzeniaAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeSrwUrzadzeniaAsync(object userState) {
            if ((this.ZwrocListeSrwUrzadzeniaOperationCompleted == null)) {
                this.ZwrocListeSrwUrzadzeniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeSrwUrzadzeniaOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeSrwUrzadzenia", new object[0], this.ZwrocListeSrwUrzadzeniaOperationCompleted, userState);
        }
        
        private void OnZwrocListeSrwUrzadzeniaOperationCompleted(object arg) {
            if ((this.ZwrocListeSrwUrzadzeniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeSrwUrzadzeniaCompleted(this, new ZwrocListeSrwUrzadzeniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeSrwUrzRodzPar", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeSrwUrzRodzPar() {
            object[] results = this.Invoke("ZwrocListeSrwUrzRodzPar", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeSrwUrzRodzParAsync() {
            this.ZwrocListeSrwUrzRodzParAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeSrwUrzRodzParAsync(object userState) {
            if ((this.ZwrocListeSrwUrzRodzParOperationCompleted == null)) {
                this.ZwrocListeSrwUrzRodzParOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeSrwUrzRodzParOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeSrwUrzRodzPar", new object[0], this.ZwrocListeSrwUrzRodzParOperationCompleted, userState);
        }
        
        private void OnZwrocListeSrwUrzRodzParOperationCompleted(object arg) {
            if ((this.ZwrocListeSrwUrzRodzParCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeSrwUrzRodzParCompleted(this, new ZwrocListeSrwUrzRodzParCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeSrwUrzParDef", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeSrwUrzParDef() {
            object[] results = this.Invoke("ZwrocListeSrwUrzParDef", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeSrwUrzParDefAsync() {
            this.ZwrocListeSrwUrzParDefAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeSrwUrzParDefAsync(object userState) {
            if ((this.ZwrocListeSrwUrzParDefOperationCompleted == null)) {
                this.ZwrocListeSrwUrzParDefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeSrwUrzParDefOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeSrwUrzParDef", new object[0], this.ZwrocListeSrwUrzParDefOperationCompleted, userState);
        }
        
        private void OnZwrocListeSrwUrzParDefOperationCompleted(object arg) {
            if ((this.ZwrocListeSrwUrzParDefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeSrwUrzParDefCompleted(this, new ZwrocListeSrwUrzParDefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListePodpisow", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListePodpisow() {
            object[] results = this.Invoke("ZwrocListePodpisow", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListePodpisowAsync() {
            this.ZwrocListePodpisowAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListePodpisowAsync(object userState) {
            if ((this.ZwrocListePodpisowOperationCompleted == null)) {
                this.ZwrocListePodpisowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListePodpisowOperationCompleted);
            }
            this.InvokeAsync("ZwrocListePodpisow", new object[0], this.ZwrocListePodpisowOperationCompleted, userState);
        }
        
        private void OnZwrocListePodpisowOperationCompleted(object arg) {
            if ((this.ZwrocListePodpisowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListePodpisowCompleted(this, new ZwrocListePodpisowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/synchronizujSrwZlcNag", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string synchronizujSrwZlcNag(string inputJSON) {
            object[] results = this.Invoke("synchronizujSrwZlcNag", new object[] {
                        inputJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void synchronizujSrwZlcNagAsync(string inputJSON) {
            this.synchronizujSrwZlcNagAsync(inputJSON, null);
        }
        
        /// <remarks/>
        public void synchronizujSrwZlcNagAsync(string inputJSON, object userState) {
            if ((this.synchronizujSrwZlcNagOperationCompleted == null)) {
                this.synchronizujSrwZlcNagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsynchronizujSrwZlcNagOperationCompleted);
            }
            this.InvokeAsync("synchronizujSrwZlcNag", new object[] {
                        inputJSON}, this.synchronizujSrwZlcNagOperationCompleted, userState);
        }
        
        private void OnsynchronizujSrwZlcNagOperationCompleted(object arg) {
            if ((this.synchronizujSrwZlcNagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.synchronizujSrwZlcNagCompleted(this, new synchronizujSrwZlcNagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/synchronizujSrwZlcCzynnosci", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string synchronizujSrwZlcCzynnosci(string inputJSON) {
            object[] results = this.Invoke("synchronizujSrwZlcCzynnosci", new object[] {
                        inputJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void synchronizujSrwZlcCzynnosciAsync(string inputJSON) {
            this.synchronizujSrwZlcCzynnosciAsync(inputJSON, null);
        }
        
        /// <remarks/>
        public void synchronizujSrwZlcCzynnosciAsync(string inputJSON, object userState) {
            if ((this.synchronizujSrwZlcCzynnosciOperationCompleted == null)) {
                this.synchronizujSrwZlcCzynnosciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsynchronizujSrwZlcCzynnosciOperationCompleted);
            }
            this.InvokeAsync("synchronizujSrwZlcCzynnosci", new object[] {
                        inputJSON}, this.synchronizujSrwZlcCzynnosciOperationCompleted, userState);
        }
        
        private void OnsynchronizujSrwZlcCzynnosciOperationCompleted(object arg) {
            if ((this.synchronizujSrwZlcCzynnosciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.synchronizujSrwZlcCzynnosciCompleted(this, new synchronizujSrwZlcCzynnosciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/synchronizujSrwZlcSkladniki", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string synchronizujSrwZlcSkladniki(string inputJSON) {
            object[] results = this.Invoke("synchronizujSrwZlcSkladniki", new object[] {
                        inputJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void synchronizujSrwZlcSkladnikiAsync(string inputJSON) {
            this.synchronizujSrwZlcSkladnikiAsync(inputJSON, null);
        }
        
        /// <remarks/>
        public void synchronizujSrwZlcSkladnikiAsync(string inputJSON, object userState) {
            if ((this.synchronizujSrwZlcSkladnikiOperationCompleted == null)) {
                this.synchronizujSrwZlcSkladnikiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsynchronizujSrwZlcSkladnikiOperationCompleted);
            }
            this.InvokeAsync("synchronizujSrwZlcSkladniki", new object[] {
                        inputJSON}, this.synchronizujSrwZlcSkladnikiOperationCompleted, userState);
        }
        
        private void OnsynchronizujSrwZlcSkladnikiOperationCompleted(object arg) {
            if ((this.synchronizujSrwZlcSkladnikiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.synchronizujSrwZlcSkladnikiCompleted(this, new synchronizujSrwZlcSkladnikiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/ZwrocListeOperatorow", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZwrocListeOperatorow() {
            object[] results = this.Invoke("ZwrocListeOperatorow", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocListeOperatorowAsync() {
            this.ZwrocListeOperatorowAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocListeOperatorowAsync(object userState) {
            if ((this.ZwrocListeOperatorowOperationCompleted == null)) {
                this.ZwrocListeOperatorowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocListeOperatorowOperationCompleted);
            }
            this.InvokeAsync("ZwrocListeOperatorow", new object[0], this.ZwrocListeOperatorowOperationCompleted, userState);
        }
        
        private void OnZwrocListeOperatorowOperationCompleted(object arg) {
            if ((this.ZwrocListeOperatorowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocListeOperatorowCompleted(this, new ZwrocListeOperatorowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/GalSrv_SrwZlcNag", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GalSrv_SrwZlcNag() {
            object[] results = this.Invoke("GalSrv_SrwZlcNag", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcNagAsync() {
            this.GalSrv_SrwZlcNagAsync(null);
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcNagAsync(object userState) {
            if ((this.GalSrv_SrwZlcNagOperationCompleted == null)) {
                this.GalSrv_SrwZlcNagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGalSrv_SrwZlcNagOperationCompleted);
            }
            this.InvokeAsync("GalSrv_SrwZlcNag", new object[0], this.GalSrv_SrwZlcNagOperationCompleted, userState);
        }
        
        private void OnGalSrv_SrwZlcNagOperationCompleted(object arg) {
            if ((this.GalSrv_SrwZlcNagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GalSrv_SrwZlcNagCompleted(this, new GalSrv_SrwZlcNagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/GalSrv_SrwZlcNagPotwierdzenie", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GalSrv_SrwZlcNagPotwierdzenie(string listaPotwierdzonych) {
            object[] results = this.Invoke("GalSrv_SrwZlcNagPotwierdzenie", new object[] {
                        listaPotwierdzonych});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcNagPotwierdzenieAsync(string listaPotwierdzonych) {
            this.GalSrv_SrwZlcNagPotwierdzenieAsync(listaPotwierdzonych, null);
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcNagPotwierdzenieAsync(string listaPotwierdzonych, object userState) {
            if ((this.GalSrv_SrwZlcNagPotwierdzenieOperationCompleted == null)) {
                this.GalSrv_SrwZlcNagPotwierdzenieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGalSrv_SrwZlcNagPotwierdzenieOperationCompleted);
            }
            this.InvokeAsync("GalSrv_SrwZlcNagPotwierdzenie", new object[] {
                        listaPotwierdzonych}, this.GalSrv_SrwZlcNagPotwierdzenieOperationCompleted, userState);
        }
        
        private void OnGalSrv_SrwZlcNagPotwierdzenieOperationCompleted(object arg) {
            if ((this.GalSrv_SrwZlcNagPotwierdzenieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GalSrv_SrwZlcNagPotwierdzenieCompleted(this, new GalSrv_SrwZlcNagPotwierdzenieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/GalSrv_SrwZlcCzynnosci", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GalSrv_SrwZlcCzynnosci() {
            object[] results = this.Invoke("GalSrv_SrwZlcCzynnosci", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcCzynnosciAsync() {
            this.GalSrv_SrwZlcCzynnosciAsync(null);
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcCzynnosciAsync(object userState) {
            if ((this.GalSrv_SrwZlcCzynnosciOperationCompleted == null)) {
                this.GalSrv_SrwZlcCzynnosciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGalSrv_SrwZlcCzynnosciOperationCompleted);
            }
            this.InvokeAsync("GalSrv_SrwZlcCzynnosci", new object[0], this.GalSrv_SrwZlcCzynnosciOperationCompleted, userState);
        }
        
        private void OnGalSrv_SrwZlcCzynnosciOperationCompleted(object arg) {
            if ((this.GalSrv_SrwZlcCzynnosciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GalSrv_SrwZlcCzynnosciCompleted(this, new GalSrv_SrwZlcCzynnosciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/GalSrv_SrwZlcCzynnosciPotwierdzenie", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GalSrv_SrwZlcCzynnosciPotwierdzenie(string listaPotwierdzonych) {
            object[] results = this.Invoke("GalSrv_SrwZlcCzynnosciPotwierdzenie", new object[] {
                        listaPotwierdzonych});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcCzynnosciPotwierdzenieAsync(string listaPotwierdzonych) {
            this.GalSrv_SrwZlcCzynnosciPotwierdzenieAsync(listaPotwierdzonych, null);
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcCzynnosciPotwierdzenieAsync(string listaPotwierdzonych, object userState) {
            if ((this.GalSrv_SrwZlcCzynnosciPotwierdzenieOperationCompleted == null)) {
                this.GalSrv_SrwZlcCzynnosciPotwierdzenieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGalSrv_SrwZlcCzynnosciPotwierdzenieOperationCompleted);
            }
            this.InvokeAsync("GalSrv_SrwZlcCzynnosciPotwierdzenie", new object[] {
                        listaPotwierdzonych}, this.GalSrv_SrwZlcCzynnosciPotwierdzenieOperationCompleted, userState);
        }
        
        private void OnGalSrv_SrwZlcCzynnosciPotwierdzenieOperationCompleted(object arg) {
            if ((this.GalSrv_SrwZlcCzynnosciPotwierdzenieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GalSrv_SrwZlcCzynnosciPotwierdzenieCompleted(this, new GalSrv_SrwZlcCzynnosciPotwierdzenieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/GalSrv_SrwZlcSkladniki", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GalSrv_SrwZlcSkladniki() {
            object[] results = this.Invoke("GalSrv_SrwZlcSkladniki", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcSkladnikiAsync() {
            this.GalSrv_SrwZlcSkladnikiAsync(null);
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcSkladnikiAsync(object userState) {
            if ((this.GalSrv_SrwZlcSkladnikiOperationCompleted == null)) {
                this.GalSrv_SrwZlcSkladnikiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGalSrv_SrwZlcSkladnikiOperationCompleted);
            }
            this.InvokeAsync("GalSrv_SrwZlcSkladniki", new object[0], this.GalSrv_SrwZlcSkladnikiOperationCompleted, userState);
        }
        
        private void OnGalSrv_SrwZlcSkladnikiOperationCompleted(object arg) {
            if ((this.GalSrv_SrwZlcSkladnikiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GalSrv_SrwZlcSkladnikiCompleted(this, new GalSrv_SrwZlcSkladnikiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("galsoftsrv/GalSrv_SrwZlcSkladnikiPotwierdzenie", RequestNamespace="galsoftsrv", ResponseNamespace="galsoftsrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GalSrv_SrwZlcSkladnikiPotwierdzenie(string listaPotwierdzonych) {
            this.Invoke("GalSrv_SrwZlcSkladnikiPotwierdzenie", new object[] {
                        listaPotwierdzonych});
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcSkladnikiPotwierdzenieAsync(string listaPotwierdzonych) {
            this.GalSrv_SrwZlcSkladnikiPotwierdzenieAsync(listaPotwierdzonych, null);
        }
        
        /// <remarks/>
        public void GalSrv_SrwZlcSkladnikiPotwierdzenieAsync(string listaPotwierdzonych, object userState) {
            if ((this.GalSrv_SrwZlcSkladnikiPotwierdzenieOperationCompleted == null)) {
                this.GalSrv_SrwZlcSkladnikiPotwierdzenieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGalSrv_SrwZlcSkladnikiPotwierdzenieOperationCompleted);
            }
            this.InvokeAsync("GalSrv_SrwZlcSkladnikiPotwierdzenie", new object[] {
                        listaPotwierdzonych}, this.GalSrv_SrwZlcSkladnikiPotwierdzenieOperationCompleted, userState);
        }
        
        private void OnGalSrv_SrwZlcSkladnikiPotwierdzenieOperationCompleted(object arg) {
            if ((this.GalSrv_SrwZlcSkladnikiPotwierdzenieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GalSrv_SrwZlcSkladnikiPotwierdzenieCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SayHelloToLameCompletedEventHandler(object sender, SayHelloToLameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SayHelloToLameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SayHelloToLameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void lamaCompletedEventHandler(object sender, lamaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lamaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lamaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeKntAdresyCompletedEventHandler(object sender, ZwrocListeKntAdresyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeKntAdresyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeKntAdresyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeKntKartyCompletedEventHandler(object sender, ZwrocListeKntKartyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeKntKartyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeKntKartyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeZlecenSerwisowychNaglowkiCompletedEventHandler(object sender, ZwrocListeZlecenSerwisowychNaglowkiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeZlecenSerwisowychNaglowkiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeZlecenSerwisowychNaglowkiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeZlecenSerwisowychCzynnosciCompletedEventHandler(object sender, ZwrocListeZlecenSerwisowychCzynnosciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeZlecenSerwisowychCzynnosciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeZlecenSerwisowychCzynnosciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeZlecenSerwisowychSkladnikiCompletedEventHandler(object sender, ZwrocListeZlecenSerwisowychSkladnikiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeZlecenSerwisowychSkladnikiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeZlecenSerwisowychSkladnikiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeTwrKartyCompletedEventHandler(object sender, ZwrocListeTwrKartyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeTwrKartyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeTwrKartyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeSrwUrzRodzajeCompletedEventHandler(object sender, ZwrocListeSrwUrzRodzajeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeSrwUrzRodzajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeSrwUrzRodzajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeSrwUrzadzeniaCompletedEventHandler(object sender, ZwrocListeSrwUrzadzeniaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeSrwUrzadzeniaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeSrwUrzadzeniaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeSrwUrzRodzParCompletedEventHandler(object sender, ZwrocListeSrwUrzRodzParCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeSrwUrzRodzParCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeSrwUrzRodzParCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeSrwUrzParDefCompletedEventHandler(object sender, ZwrocListeSrwUrzParDefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeSrwUrzParDefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeSrwUrzParDefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListePodpisowCompletedEventHandler(object sender, ZwrocListePodpisowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListePodpisowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListePodpisowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void synchronizujSrwZlcNagCompletedEventHandler(object sender, synchronizujSrwZlcNagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class synchronizujSrwZlcNagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal synchronizujSrwZlcNagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void synchronizujSrwZlcCzynnosciCompletedEventHandler(object sender, synchronizujSrwZlcCzynnosciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class synchronizujSrwZlcCzynnosciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal synchronizujSrwZlcCzynnosciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void synchronizujSrwZlcSkladnikiCompletedEventHandler(object sender, synchronizujSrwZlcSkladnikiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class synchronizujSrwZlcSkladnikiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal synchronizujSrwZlcSkladnikiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZwrocListeOperatorowCompletedEventHandler(object sender, ZwrocListeOperatorowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocListeOperatorowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocListeOperatorowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GalSrv_SrwZlcNagCompletedEventHandler(object sender, GalSrv_SrwZlcNagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GalSrv_SrwZlcNagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GalSrv_SrwZlcNagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GalSrv_SrwZlcNagPotwierdzenieCompletedEventHandler(object sender, GalSrv_SrwZlcNagPotwierdzenieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GalSrv_SrwZlcNagPotwierdzenieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GalSrv_SrwZlcNagPotwierdzenieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GalSrv_SrwZlcCzynnosciCompletedEventHandler(object sender, GalSrv_SrwZlcCzynnosciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GalSrv_SrwZlcCzynnosciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GalSrv_SrwZlcCzynnosciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GalSrv_SrwZlcCzynnosciPotwierdzenieCompletedEventHandler(object sender, GalSrv_SrwZlcCzynnosciPotwierdzenieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GalSrv_SrwZlcCzynnosciPotwierdzenieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GalSrv_SrwZlcCzynnosciPotwierdzenieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GalSrv_SrwZlcSkladnikiCompletedEventHandler(object sender, GalSrv_SrwZlcSkladnikiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GalSrv_SrwZlcSkladnikiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GalSrv_SrwZlcSkladnikiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GalSrv_SrwZlcSkladnikiPotwierdzenieCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591