#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AplikacjaSerwisowa.Resource", IsApplication=true)]

namespace AplikacjaSerwisowa
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int kontrahenci = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int lista_zlecen = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logowanie = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int magazyn = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int question_mark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int synchronizacja = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ustawienia = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int wykonane_czesciowe_ListaZlecen = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int wykonane_ListaZlecen = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002b
			public const int adresKodPKontrahenciRowTextView = 2131099691;
			
			// aapt resource value: 0x7f060044
			public const int adresSerwerSynchronizacja_EditText = 2131099716;
			
			// aapt resource value: 0x7f06004d
			public const int adresSerwer_EditText = 2131099725;
			
			// aapt resource value: 0x7f060043
			public const int adresSerwer_textView = 2131099715;
			
			// aapt resource value: 0x7f060037
			public const int adresTextView = 2131099703;
			
			// aapt resource value: 0x7f060002
			public const int akronimFrag1TextView = 2131099650;
			
			// aapt resource value: 0x7f060020
			public const int akronimKartyTowaroweRowTextView = 2131099680;
			
			// aapt resource value: 0x7f060026
			public const int akronimKontrahenciRowTextView = 2131099686;
			
			// aapt resource value: 0x7f060019
			public const int button1 = 2131099673;
			
			// aapt resource value: 0x7f060027
			public const int daneKontrahenta1inearLayout = 2131099687;
			
			// aapt resource value: 0x7f06002a
			public const int daneKontrahenta2LinearLayout = 2131099690;
			
			// aapt resource value: 0x7f060034
			public const int dataTextView = 2131099700;
			
			// aapt resource value: 0x7f060018
			public const int editText1 = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int emailFrag1TextView = 2131099668;
			
			// aapt resource value: 0x7f06002c
			public const int emailKontrahenciRowsTextView = 2131099692;
			
			// aapt resource value: 0x7f060013
			public const int emailNazwaFrag1TextView = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int faxFrag1TextView = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int faxNazwaFrag1TextView = 2131099665;
			
			// aapt resource value: 0x7f060017
			public const int gidNumerFrag1TextView = 2131099671;
			
			// aapt resource value: 0x7f060023
			public const int gidNumerKartyTowaroweRowTextView = 2131099683;
			
			// aapt resource value: 0x7f06002e
			public const int gidNumerKontrahenciRowTextView = 2131099694;
			
			// aapt resource value: 0x7f060038
			public const int godzinaTextView = 2131099704;
			
			// aapt resource value: 0x7f060049
			public const int hasloSerwerSynchronizacja_EditText = 2131099721;
			
			// aapt resource value: 0x7f060050
			public const int hasloSerwer_EditText = 2131099728;
			
			// aapt resource value: 0x7f06003d
			public const int haslo_EditText = 2131099709;
			
			// aapt resource value: 0x7f06003c
			public const int haslo_textView = 2131099708;
			
			// aapt resource value: 0x7f060046
			public const int instancjaSerwerSynchronizacja_EditText = 2131099718;
			
			// aapt resource value: 0x7f06004e
			public const int instancjaSerwer_EditText = 2131099726;
			
			// aapt resource value: 0x7f060045
			public const int instancjaSerwer_textView = 2131099717;
			
			// aapt resource value: 0x7f060042
			public const int item_title = 2131099714;
			
			// aapt resource value: 0x7f060039
			public const int kartyTowarowListView = 2131099705;
			
			// aapt resource value: 0x7f060007
			public const int kodPMiastoFrag1TextView = 2131099655;
			
			// aapt resource value: 0x7f060025
			public const int kontrahenciListView = 2131099685;
			
			// aapt resource value: 0x7f06001e
			public const int kontrahenci_Button = 2131099678;
			
			// aapt resource value: 0x7f060033
			public const int kontrahentTextView = 2131099699;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout1 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout2 = 2131099662;
			
			// aapt resource value: 0x7f060036
			public const int linearLayout3 = 2131099702;
			
			// aapt resource value: 0x7f060031
			public const int listView1 = 2131099697;
			
			// aapt resource value: 0x7f06001d
			public const int listaZlecen_Button = 2131099677;
			
			// aapt resource value: 0x7f06003f
			public const int loadingPanel = 2131099711;
			
			// aapt resource value: 0x7f060048
			public const int loginSerwerSynchronizacja_EditText = 2131099720;
			
			// aapt resource value: 0x7f06004f
			public const int loginSerwer_EditText = 2131099727;
			
			// aapt resource value: 0x7f060047
			public const int loginSerwer_textView = 2131099719;
			
			// aapt resource value: 0x7f06003b
			public const int login_EditText = 2131099707;
			
			// aapt resource value: 0x7f06001f
			public const int magazyn_Button = 2131099679;
			
			// aapt resource value: 0x7f060004
			public const int nazwaFrag1TextView = 2131099652;
			
			// aapt resource value: 0x7f060021
			public const int nazwaKartyTowaroweRowTextView = 2131099681;
			
			// aapt resource value: 0x7f060003
			public const int nazwaTextView = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int nipFrag1TextView = 2131099657;
			
			// aapt resource value: 0x7f06001c
			public const int noweZlecenie_Button = 2131099676;
			
			// aapt resource value: 0x7f060022
			public const int parametryKartyTowarowLinearLayout = 2131099682;
			
			// aapt resource value: 0x7f06002d
			public const int parametryKontrahenciLinearLayout = 2131099693;
			
			// aapt resource value: 0x7f060032
			public const int realizacjaImageView = 2131099698;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06002f
			public const int sample_main_layout = 2131099695;
			
			// aapt resource value: 0x7f06001a
			public const int sliding_tabs = 2131099674;
			
			// aapt resource value: 0x7f060052
			public const int synchronizacjaButton = 2131099730;
			
			// aapt resource value: 0x7f06004b
			public const int synchronizacjaSynchronizacjaButton = 2131099723;
			
			// aapt resource value: 0x7f060054
			public const int synchronizacja_glowneOknoMenu = 2131099732;
			
			// aapt resource value: 0x7f06000c
			public const int telefon1Frag1TextView = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int telefon2Frag1TextView = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int telefon3Frag1TextView = 2131099664;
			
			// aapt resource value: 0x7f060029
			public const int telefonKontrahenciRowTextView = 2131099689;
			
			// aapt resource value: 0x7f06000a
			public const int telefonNazwaFrag1TextView = 2131099658;
			
			// aapt resource value: 0x7f060035
			public const int telefonTextView = 2131099701;
			
			// aapt resource value: 0x7f06000f
			public const int telexFrag1TextView = 2131099663;
			
			// aapt resource value: 0x7f06004c
			public const int test2Synchronizacja_button = 2131099724;
			
			// aapt resource value: 0x7f060053
			public const int test2_button = 2131099731;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int textView5 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int textView8 = 2131099656;
			
			// aapt resource value: 0x7f060024
			public const int typKartyTowaroweRowsTextView = 2131099684;
			
			// aapt resource value: 0x7f060006
			public const int ulicaFrag1TextView = 2131099654;
			
			// aapt resource value: 0x7f060028
			public const int ulicaKontrahenciRowTextView = 2131099688;
			
			// aapt resource value: 0x7f060016
			public const int urlFrag1TextView = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int urlNazwaFrag1TextView = 2131099669;
			
			// aapt resource value: 0x7f060057
			public const int ustawienia_mainActivityMenu = 2131099735;
			
			// aapt resource value: 0x7f060041
			public const int uzupelnijTestButton = 2131099713;
			
			// aapt resource value: 0x7f060030
			public const int viewPager = 2131099696;
			
			// aapt resource value: 0x7f06001b
			public const int viewpager = 2131099675;
			
			// aapt resource value: 0x7f060040
			public const int wszyscyButton = 2131099712;
			
			// aapt resource value: 0x7f060055
			public const int wyloguj_glowneOknoMenu = 2131099733;
			
			// aapt resource value: 0x7f06003e
			public const int zaloguj_Button = 2131099710;
			
			// aapt resource value: 0x7f06003a
			public const int zaloguj_textView = 2131099706;
			
			// aapt resource value: 0x7f060056
			public const int zamknij_glowneOknoMenu = 2131099734;
			
			// aapt resource value: 0x7f060058
			public const int zamknij_mainActivityMenu = 2131099736;
			
			// aapt resource value: 0x7f06004a
			public const int zapiszSerwerSynchronizacja_Button = 2131099722;
			
			// aapt resource value: 0x7f060051
			public const int zapiszSerwer_Button = 2131099729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Frag1Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Frag2Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Frag3Layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_sample = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int glowneOkno = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int kartyTowarow_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int kontrahenci = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int kontrahenci_row = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int kontrahenciInformacje = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int listaZlecen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int listview_row = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int magazyn = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int noweZlecenie = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int pager_item = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int synchronizacjaOkno = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ustawienia = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int glowneOkno_Menu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mainActivity_Menu = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
